version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 1
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: ~/web
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Running linter
          command: yarn lint
      - run:
          name: Running unit tests
          command: yarn test:coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
      - codecov/upload:
          file: coverage/*.json
  build:
    docker:
      - image: circleci/node
    parallelism: 1
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: ~/web
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Building project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    docker:
      - image: circleci/node
    parallelism: 1
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: ~/web
      - run:
          name: List dist directory
          command: ls -la dist/
      - run:
          name: Install and configure dependencies
          command: |
            yarn global add gh-pages
            git config user.email "ci-build@catolicasc.org.br"
            git config user.name "CI Build"
      - run:
          name: Deploy to GH Pages
          command: gh-pages --dist dist/

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build
          # filters:
          #   branches:
          #     only: master
