version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 3
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: ~/web
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Running linter
          command: yarn lint
      - run:
          name: Running unit tests
          command: yarn test:coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
      - codecov/upload:
          file: coverage/*.json
  build:
    docker:
      - image: circleci/node
    parallelism: 3
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: ~/web
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Building project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: dist

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
